export enum CategoryType {
    Spendings,
    Income,
    CNWRouteType,
    Vehicles,
    Maintenance,
    IncomeSources,
    Freelancing,
    InterestFeesCharges,
    Shopping,
    FoodDrinks,
    Travel,
    Services,
    Holiday,
    ReminderTypes,
    Savings,
}
