export enum Page {
    Home = "Home",
    Login = "Login",
    Register = "Register",
    ResetPassword = "Reset Password",
    Products = "Catalog",
    Product = "Product Info",
    Cart = "Cart",
    Contacts = "Contacts",
    OrderSuccess = "Order Success",
    Order = "Order",
    Account = "Account",
    Addresses = "addresses",
    ProductImport = "Product Import",
}
